version: "3.8"

services:
  mysql-db:
    # build:
    #   context: ./database
    #   dockerfile: Dockerfile
    image: mysql:8.4
    container_name: mysql_db
    ports:
      - "3306:3306"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=TTM
      - MYSQL_USER=moaaz
      - MYSQL_PASSWORD=moaazkaff

volumes:
  mysql-volume:
